//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkonomiDataAccess1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemaKoppling
    {
        public int Id { get; set; }
        public int PersonalSchemaID { get; set; }
        public int PersonalID { get; set; }
    
        public virtual PersonalSchema PersonalSchema { get; set; }
    }
}
